// Generated by ../generate-journal-events.mjs; do not edit.
include "Journal.dfy"

function EventWitnesses(): seq<Event>
{
  [
    Act(ClaimIntentRecorded(A, 0)),
    Act(ClaimReleaseIntentRecorded(A, 0)),
    Act(AttemptPlanned(A, 0, 0)),
    Act(WorkAdmitted(A, 0)),
    Act(SuspensionRequested(A, 0)),
    Act(ResumeRequested(A, 0)),
    Act(WorktreeIntentRecorded(A, 0)),
    Act(IntegrationSessionOpened(A, 0)),
    Act(PromotionIntentRecorded(A, 0)),
    Act(CandidateConstructionNonConvergent(A, StaleTargetHead)),
    Act(DeliverySettled(A)),
    Act(WorkflowRunBegun(0, 0)),
    Act(WorkflowRunTerminated(0)),
    Act(CapacityRevised(0)),
    Act(DirectionApplied(0, Pause)),
    Occ(TrackerFactsObserved([], [], true, 0)),
    Occ(ClaimRecordRead(A, 0, 0)),
    Occ(ClaimedTaskEligibilityObserved(A, 0)),
    Occ(ClaimedTaskIneligible(A, NotOpen)),
    Occ(WorktreeReconciliationObserved(A, 0, Created)),
    Occ(ExecutorReported(A, 0, Running)),
    Occ(PromotionOutcomeObserved(A, 0)),
    Occ(TargetHeadObserved(0))
  ]
}

lemma EventWitnessCount()
  ensures |EventWitnesses()| == 23
{}
