import type { TaskDagRevision } from "./trace-contract.ts";

export const TRACKER_SNAPSHOT_CAPTURED_AT = "2026-07-18T21:01:25Z";

export const trackerTaskDagSnapshot = {
  revision: "tracker-revision:github-issue-12-04f996b64663a5e0",
  tasks: [
    {
      id: "github-issue:12",
      title:
        "Specification: Language-neutral Cleanroom SDK readiness and acceptance",
      lifecycle: "open",
      parentTaskId: null,
      prerequisiteIds: [],
      assignment: { tag: "Unassigned" },
      labels: [],
    },
    {
      id: "github-issue:13",
      title: "Classify failing quality gates against Cleanroom architecture",
      lifecycle: "closed",
      parentTaskId: "github-issue:12",
      prerequisiteIds: [],
      assignment: { tag: "Assigned", owner: "dearlordylord" },
      labels: [],
    },
    {
      id: "github-issue:14",
      title: "Audit the authoritative Surface decoding and admission boundary",
      lifecycle: "closed",
      parentTaskId: "github-issue:12",
      prerequisiteIds: [],
      assignment: { tag: "Assigned", owner: "dearlordylord" },
      labels: [],
    },
    {
      id: "github-issue:15",
      title: "Audit QNT semantics for accidental content combinatorics",
      lifecycle: "closed",
      parentTaskId: "github-issue:12",
      prerequisiteIds: [],
      assignment: { tag: "Assigned", owner: "dearlordylord" },
      labels: [],
    },
    {
      id: "github-issue:16",
      title: "Trace QNT conformance through reducers and SDK workflows",
      lifecycle: "closed",
      parentTaskId: "github-issue:12",
      prerequisiteIds: [],
      assignment: { tag: "Assigned", owner: "dearlordylord" },
      labels: [],
    },
    {
      id: "github-issue:17",
      title: "Define Static Mechanics Admission and dynamic availability",
      lifecycle: "closed",
      parentTaskId: "github-issue:12",
      prerequisiteIds: ["github-issue:14", "github-issue:13"],
      assignment: { tag: "Assigned", owner: "dearlordylord" },
      labels: [],
    },
    {
      id: "github-issue:18",
      title: "Define the portable Surface content contract",
      lifecycle: "closed",
      parentTaskId: "github-issue:12",
      prerequisiteIds: ["github-issue:14"],
      assignment: { tag: "Assigned", owner: "dearlordylord" },
      labels: [],
    },
    {
      id: "github-issue:19",
      title: "Define comprehensive QNT conformance",
      lifecycle: "closed",
      parentTaskId: "github-issue:12",
      prerequisiteIds: ["github-issue:16", "github-issue:15"],
      assignment: { tag: "Assigned", owner: "dearlordylord" },
      labels: [],
    },
    {
      id: "github-issue:20",
      title: "Define the Cleanroom Core and Target Language Adapter boundary",
      lifecycle: "closed",
      parentTaskId: "github-issue:12",
      prerequisiteIds: [
        "github-issue:22",
        "github-issue:19",
        "github-issue:18",
        "github-issue:17",
      ],
      assignment: { tag: "Assigned", owner: "dearlordylord" },
      labels: [],
    },
    {
      id: "github-issue:21",
      title: "Define source readiness and the Target SDK foundation handoff",
      lifecycle: "closed",
      parentTaskId: "github-issue:12",
      prerequisiteIds: ["github-issue:20", "github-issue:13"],
      assignment: { tag: "Assigned", owner: "dearlordylord" },
      labels: [],
    },
    {
      id: "github-issue:22",
      title: "Define the Opaque Oracle conformance boundary",
      lifecycle: "closed",
      parentTaskId: "github-issue:12",
      prerequisiteIds: [],
      assignment: { tag: "Assigned", owner: "dearlordylord" },
      labels: [],
    },
    {
      id: "github-issue:23",
      title: "Define the Oracle Case and Trace algebra",
      lifecycle: "closed",
      parentTaskId: "github-issue:12",
      prerequisiteIds: [],
      assignment: { tag: "Assigned", owner: "dearlordylord" },
      labels: [],
    },
    {
      id: "github-issue:24",
      title: "Reconcile the cleanroom rules corpus, language, and licensing",
      lifecycle: "open",
      parentTaskId: "github-issue:12",
      prerequisiteIds: [],
      assignment: { tag: "Unassigned" },
      labels: [],
    },
    {
      id: "github-issue:25",
      title: "Repair the nine canonical RAW-to-Surface catalog omissions",
      lifecycle: "closed",
      parentTaskId: "github-issue:12",
      prerequisiteIds: [],
      assignment: { tag: "Unassigned" },
      labels: ["ready-for-agent"],
    },
    {
      id: "github-issue:26",
      title:
        "Make canonical Surface publication complete, strict, and portable",
      lifecycle: "open",
      parentTaskId: "github-issue:12",
      prerequisiteIds: [],
      assignment: { tag: "Unassigned" },
      labels: [],
    },
    {
      id: "github-issue:27",
      title:
        "Replace authored-identity mechanics dispatch with typed procedure facts",
      lifecycle: "open",
      parentTaskId: "github-issue:12",
      prerequisiteIds: [],
      assignment: { tag: "Unassigned" },
      labels: [],
    },
    {
      id: "github-issue:28",
      title:
        "Install decoded catalogs through atomic Static Mechanics Admission",
      lifecycle: "open",
      parentTaskId: "github-issue:12",
      prerequisiteIds: [],
      assignment: { tag: "Unassigned" },
      labels: [],
    },
    {
      id: "github-issue:29",
      title: "Generate the complete Cleanroom Mechanics Slice",
      lifecycle: "open",
      parentTaskId: "github-issue:12",
      prerequisiteIds: ["github-issue:118"],
      assignment: { tag: "Unassigned" },
      labels: ["ready-for-agent"],
    },
    {
      id: "github-issue:30",
      title:
        "Generalize interrupted-procedure QNT semantics by capability and phase",
      lifecycle: "open",
      parentTaskId: "github-issue:12",
      prerequisiteIds: [],
      assignment: { tag: "Unassigned" },
      labels: [],
    },
    {
      id: "github-issue:31",
      title:
        "Derive executable QNT conformance closure through production reducers",
      lifecycle: "open",
      parentTaskId: "github-issue:12",
      prerequisiteIds: [],
      assignment: { tag: "Unassigned" },
      labels: [],
    },
    {
      id: "github-issue:32",
      title:
        "Add the typed stateless Oracle Case-to-Trace production operation",
      lifecycle: "open",
      parentTaskId: "github-issue:12",
      prerequisiteIds: [],
      assignment: { tag: "Unassigned" },
      labels: [],
    },
    {
      id: "github-issue:33",
      title: "Expose equivalent Oracle CLI and HTTP batch surfaces",
      lifecycle: "open",
      parentTaskId: "github-issue:12",
      prerequisiteIds: [],
      assignment: { tag: "Unassigned" },
      labels: [],
    },
    {
      id: "github-issue:34",
      title: "Publish the single language-neutral Cleanroom Core",
      lifecycle: "open",
      parentTaskId: "github-issue:12",
      prerequisiteIds: [
        "github-issue:122",
        "github-issue:60",
        "github-issue:29",
        "github-issue:97",
      ],
      assignment: { tag: "Unassigned" },
      labels: ["ready-for-agent"],
    },
    {
      id: "github-issue:35",
      title: "Publish the minimal Rust Target Language Adapter",
      lifecycle: "open",
      parentTaskId: "github-issue:12",
      prerequisiteIds: ["github-issue:40", "github-issue:34"],
      assignment: { tag: "Unassigned" },
      labels: ["ready-for-agent"],
    },
    {
      id: "github-issue:36",
      title: "Assemble the source-produced Cleanroom Harness",
      lifecycle: "open",
      parentTaskId: "github-issue:12",
      prerequisiteIds: [
        "github-issue:40",
        "github-issue:35",
        "github-issue:34",
      ],
      assignment: { tag: "Unassigned" },
      labels: ["ready-for-agent"],
    },
    {
      id: "github-issue:37",
      title: "Run a Dirty-Cleanroom Rehearsal and repair the declared inputs",
      lifecycle: "open",
      parentTaskId: "github-issue:12",
      prerequisiteIds: [],
      assignment: { tag: "Unassigned" },
      labels: [],
    },
    {
      id: "github-issue:38",
      title: "Establish atomic Source Readiness from one coherent source state",
      lifecycle: "open",
      parentTaskId: "github-issue:12",
      prerequisiteIds: [],
      assignment: { tag: "Unassigned" },
      labels: [],
    },
    {
      id: "github-issue:39",
      title: "Perform the final fresh-folder Cleanroom Acceptance Run",
      lifecycle: "open",
      parentTaskId: "github-issue:12",
      prerequisiteIds: [],
      assignment: { tag: "Unassigned" },
      labels: [],
    },
    {
      id: "github-issue:40",
      title: "Package the calibrated source-free Opaque Oracle distribution",
      lifecycle: "open",
      parentTaskId: "github-issue:12",
      prerequisiteIds: [
        "github-issue:66",
        "github-issue:60",
        "github-issue:29",
      ],
      assignment: { tag: "Unassigned" },
      labels: ["ready-for-agent"],
    },
    {
      id: "github-issue:41",
      title: "Reconcile shared D&D language to SRD 5.2.1",
      lifecycle: "closed",
      parentTaskId: "github-issue:24",
      prerequisiteIds: [],
      assignment: { tag: "Unassigned" },
      labels: ["ready-for-agent"],
    },
    {
      id: "github-issue:42",
      title: "Curate source-ready cleanroom modeling assumptions",
      lifecycle: "closed",
      parentTaskId: "github-issue:24",
      prerequisiteIds: [],
      assignment: { tag: "Unassigned" },
      labels: ["ready-for-agent"],
    },
    {
      id: "github-issue:43",
      title: "Audit redistributable cleanroom rules, identity, and licensing",
      lifecycle: "open",
      parentTaskId: "github-issue:24",
      prerequisiteIds: [],
      assignment: { tag: "Unassigned" },
      labels: [],
    },
    {
      id: "github-issue:44",
      title: "Enforce complete canonical Surface discovery and regeneration",
      lifecycle: "closed",
      parentTaskId: "github-issue:26",
      prerequisiteIds: ["github-issue:25"],
      assignment: { tag: "Unassigned" },
      labels: ["ready-for-agent"],
    },
    {
      id: "github-issue:45",
      title:
        "Publish the strict SRD Surface aggregate and Draft 2020-12 schema",
      lifecycle: "open",
      parentTaskId: "github-issue:26",
      prerequisiteIds: [],
      assignment: { tag: "Unassigned" },
      labels: [],
    },
    {
      id: "github-issue:46",
      title: "Prove portable Surface decoding and atomic rejection",
      lifecycle: "open",
      parentTaskId: "github-issue:26",
      prerequisiteIds: ["github-issue:98"],
      assignment: { tag: "Unassigned" },
      labels: ["ready-for-agent"],
    },
    {
      id: "github-issue:47",
      title: "Drive spell execution from typed procedure facts",
      lifecycle: "closed",
      parentTaskId: "github-issue:27",
      prerequisiteIds: ["github-issue:25"],
      assignment: { tag: "Unassigned" },
      labels: ["ready-for-agent"],
    },
    {
      id: "github-issue:48",
      title: "Drive Unit mechanics from typed support profiles",
      lifecycle: "open",
      parentTaskId: "github-issue:27",
      prerequisiteIds: [],
      assignment: { tag: "Unassigned" },
      labels: [],
    },
    {
      id: "github-issue:49",
      title: "Drive Stat Block mechanics from typed support profiles",
      lifecycle: "open",
      parentTaskId: "github-issue:27",
      prerequisiteIds: [],
      assignment: { tag: "Unassigned" },
      labels: [],
    },
    {
      id: "github-issue:50",
      title:
        "Close composition and character-sheet authored-identity boundaries",
      lifecycle: "open",
      parentTaskId: "github-issue:27",
      prerequisiteIds: [],
      assignment: { tag: "Unassigned" },
      labels: [],
    },
    {
      id: "github-issue:51",
      title:
        "Introduce the atomic catalog-install and admission result boundary",
      lifecycle: "open",
      parentTaskId: "github-issue:28",
      prerequisiteIds: ["github-issue:116", "github-issue:46"],
      assignment: { tag: "Unassigned" },
      labels: ["ready-for-agent"],
    },
    {
      id: "github-issue:52",
      title: "Admit complete Unit Authored Mechanics Graphs",
      lifecycle: "open",
      parentTaskId: "github-issue:28",
      prerequisiteIds: ["github-issue:51"],
      assignment: { tag: "Unassigned" },
      labels: ["ready-for-agent"],
    },
    {
      id: "github-issue:53",
      title: "Admit complete Stat Block Authored Mechanics Graphs",
      lifecycle: "open",
      parentTaskId: "github-issue:28",
      prerequisiteIds: ["github-issue:51"],
      assignment: { tag: "Unassigned" },
      labels: ["ready-for-agent"],
    },
    {
      id: "github-issue:54",
      title: "Consume admitted mechanics in binding and dynamic availability",
      lifecycle: "open",
      parentTaskId: "github-issue:28",
      prerequisiteIds: [],
      assignment: { tag: "Unassigned" },
      labels: [],
    },
    {
      id: "github-issue:55",
      title: "Capture interrupted-procedure facts in QNT and production state",
      lifecycle: "open",
      parentTaskId: "github-issue:30",
      prerequisiteIds: [],
      assignment: { tag: "Unassigned" },
      labels: [],
    },
    {
      id: "github-issue:56",
      title: "Resume Shield-interrupted procedures by capability and phase",
      lifecycle: "open",
      parentTaskId: "github-issue:30",
      prerequisiteIds: ["github-issue:104", "github-issue:102"],
      assignment: { tag: "Unassigned" },
      labels: ["ready-for-agent"],
    },
    {
      id: "github-issue:57",
      title: "Calibrate typed cross-record and shared lifecycle interactions",
      lifecycle: "open",
      parentTaskId: "github-issue:30",
      prerequisiteIds: [],
      assignment: { tag: "Unassigned" },
      labels: [],
    },
    {
      id: "github-issue:58",
      title: "Derive the active executable QNT root and semantic closure",
      lifecycle: "open",
      parentTaskId: "github-issue:31",
      prerequisiteIds: [
        "github-issue:108",
        "github-issue:120",
        "github-issue:119",
        "github-issue:29",
      ],
      assignment: { tag: "Unassigned" },
      labels: ["ready-for-agent"],
    },
    {
      id: "github-issue:59",
      title: "Execute every derived QNT root in its real lane",
      lifecycle: "open",
      parentTaskId: "github-issue:31",
      prerequisiteIds: ["github-issue:58"],
      assignment: { tag: "Unassigned" },
      labels: ["ready-for-agent"],
    },
    {
      id: "github-issue:60",
      title:
        "Replay runtime-bearing QNT through production Functional Reducers",
      lifecycle: "open",
      parentTaskId: "github-issue:31",
      prerequisiteIds: ["github-issue:59"],
      assignment: { tag: "Unassigned" },
      labels: ["ready-for-agent"],
    },
    {
      id: "github-issue:61",
      title: "Define the strict Oracle Case and Trace algebra",
      lifecycle: "open",
      parentTaskId: "github-issue:32",
      prerequisiteIds: [],
      assignment: { tag: "Unassigned" },
      labels: [],
    },
    {
      id: "github-issue:62",
      title: "Run stateless Character Creation through fresh Character Sheet",
      lifecycle: "open",
      parentTaskId: "github-issue:32",
      prerequisiteIds: ["github-issue:95"],
      assignment: { tag: "Unassigned" },
      labels: ["ready-for-agent"],
    },
    {
      id: "github-issue:63",
      title: "Run stateless Battle entry, Acts, and Runtime Hole continuations",
      lifecycle: "open",
      parentTaskId: "github-issue:32",
      prerequisiteIds: [],
      assignment: { tag: "Unassigned" },
      labels: [],
    },
    {
      id: "github-issue:64",
      title: "Expose persistent Oracle CLI identity and batch evaluation",
      lifecycle: "open",
      parentTaskId: "github-issue:33",
      prerequisiteIds: ["github-issue:122"],
      assignment: { tag: "Unassigned" },
      labels: ["ready-for-agent"],
    },
    {
      id: "github-issue:65",
      title:
        "Expose and launch the loopback Oracle HTTP identity and batch service",
      lifecycle: "open",
      parentTaskId: "github-issue:33",
      prerequisiteIds: ["github-issue:122"],
      assignment: { tag: "Unassigned" },
      labels: ["ready-for-agent"],
    },
    {
      id: "github-issue:66",
      title: "Prove Oracle transport equivalence and atomic failure behavior",
      lifecycle: "open",
      parentTaskId: "github-issue:33",
      prerequisiteIds: ["github-issue:65", "github-issue:64"],
      assignment: { tag: "Unassigned" },
      labels: ["ready-for-agent"],
    },
    {
      id: "github-issue:92",
      title: "Derive presentation-free Oracle facts from production owners",
      lifecycle: "open",
      parentTaskId: "github-issue:61",
      prerequisiteIds: [],
      assignment: { tag: "Unassigned" },
      labels: [],
    },
    {
      id: "github-issue:93",
      title: "Compose the lifecycle-safe Oracle Case and Trace wire algebra",
      lifecycle: "open",
      parentTaskId: "github-issue:61",
      prerequisiteIds: [
        "github-issue:168",
        "github-issue:160",
        "github-issue:159",
        "github-issue:158",
      ],
      assignment: { tag: "Unassigned" },
      labels: ["ready-for-agent"],
    },
    {
      id: "github-issue:94",
      title:
        "Publish equivalent strict Oracle schemas and canonical value semantics",
      lifecycle: "open",
      parentTaskId: "github-issue:61",
      prerequisiteIds: ["github-issue:93"],
      assignment: { tag: "Unassigned" },
      labels: ["ready-for-agent"],
    },
    {
      id: "github-issue:95",
      title:
        "Generate the portable Oracle fixture corpus through an Effect CLI",
      lifecycle: "open",
      parentTaskId: "github-issue:61",
      prerequisiteIds: ["github-issue:94"],
      assignment: { tag: "Unassigned" },
      labels: ["ready-for-agent"],
    },
    {
      id: "github-issue:96",
      title:
        "Enforce schema-owned Surface string roles with finite value traversal",
      lifecycle: "open",
      parentTaskId: "github-issue:43",
      prerequisiteIds: ["github-issue:44"],
      assignment: { tag: "Unassigned" },
      labels: [],
    },
    {
      id: "github-issue:97",
      title: "Publish the fail-closed redistributable corpus audit",
      lifecycle: "open",
      parentTaskId: "github-issue:43",
      prerequisiteIds: [
        "github-issue:42",
        "github-issue:41",
        "github-issue:96",
      ],
      assignment: { tag: "Unassigned" },
      labels: ["ready-for-agent"],
    },
    {
      id: "github-issue:98",
      title:
        "Generate the strict SRD Surface aggregate and bounded Draft 2020-12 schema pair",
      lifecycle: "closed",
      parentTaskId: "github-issue:45",
      prerequisiteIds: ["github-issue:44"],
      assignment: { tag: "Unassigned" },
      labels: [],
    },
    {
      id: "github-issue:99",
      title:
        "Publish and read the Surface pair through one atomic leased store",
      lifecycle: "open",
      parentTaskId: "github-issue:45",
      prerequisiteIds: ["github-issue:98"],
      assignment: { tag: "Unassigned" },
      labels: ["ready-for-agent"],
    },
    {
      id: "github-issue:100",
      title: "Deliver the canonical weapon-attack interruption frame",
      lifecycle: "closed",
      parentTaskId: "github-issue:55",
      prerequisiteIds: ["github-issue:47"],
      assignment: { tag: "Unassigned" },
      labels: [],
    },
    {
      id: "github-issue:101",
      title: "Select spell-cast interruption frames from typed invocations",
      lifecycle: "open",
      parentTaskId: "github-issue:55",
      prerequisiteIds: ["github-issue:100"],
      assignment: { tag: "Unassigned" },
      labels: ["ready-for-agent"],
    },
    {
      id: "github-issue:102",
      title: "Deliver spell-attack interruption frames",
      lifecycle: "open",
      parentTaskId: "github-issue:55",
      prerequisiteIds: ["github-issue:101"],
      assignment: { tag: "Unassigned" },
      labels: ["ready-for-agent"],
    },
    {
      id: "github-issue:103",
      title: "Deliver the attack-burst attack-hit interruption frame",
      lifecycle: "open",
      parentTaskId: "github-issue:55",
      prerequisiteIds: ["github-issue:101"],
      assignment: { tag: "Unassigned" },
      labels: ["ready-for-agent"],
    },
    {
      id: "github-issue:104",
      title: "Deliver the attack-burst resolution interruption frame",
      lifecycle: "open",
      parentTaskId: "github-issue:55",
      prerequisiteIds: ["github-issue:103"],
      assignment: { tag: "Unassigned" },
      labels: ["ready-for-agent"],
    },
    {
      id: "github-issue:105",
      title: "Deliver damage-only save-gated interruption frames",
      lifecycle: "open",
      parentTaskId: "github-issue:55",
      prerequisiteIds: ["github-issue:101"],
      assignment: { tag: "Unassigned" },
      labels: ["ready-for-agent"],
    },
    {
      id: "github-issue:106",
      title: "Deliver after-damage reaction interruption frames",
      lifecycle: "open",
      parentTaskId: "github-issue:55",
      prerequisiteIds: ["github-issue:105", "github-issue:101"],
      assignment: { tag: "Unassigned" },
      labels: ["ready-for-agent"],
    },
    {
      id: "github-issue:107",
      title: "Deliver reaction-forced movement interruption frames",
      lifecycle: "open",
      parentTaskId: "github-issue:55",
      prerequisiteIds: ["github-issue:106", "github-issue:105"],
      assignment: { tag: "Unassigned" },
      labels: ["ready-for-agent"],
    },
    {
      id: "github-issue:108",
      title: "Deliver next-turn command movement interruption frames",
      lifecycle: "open",
      parentTaskId: "github-issue:55",
      prerequisiteIds: ["github-issue:100"],
      assignment: { tag: "Unassigned" },
      labels: ["ready-for-agent"],
    },
    {
      id: "github-issue:109",
      title:
        "Interpret Unit progression and choice mechanics through Character Build",
      lifecycle: "open",
      parentTaskId: "github-issue:48",
      prerequisiteIds: ["github-issue:25"],
      assignment: { tag: "Unassigned" },
      labels: [],
    },
    {
      id: "github-issue:110",
      title:
        "Project Unit mechanics through Character Sheet and Battle handoff",
      lifecycle: "open",
      parentTaskId: "github-issue:48",
      prerequisiteIds: ["github-issue:109"],
      assignment: { tag: "Unassigned" },
      labels: ["ready-for-agent"],
    },
    {
      id: "github-issue:111",
      title: "Initialize Battle creatures from passive Unit mechanics",
      lifecycle: "open",
      parentTaskId: "github-issue:48",
      prerequisiteIds: ["github-issue:110"],
      assignment: { tag: "Unassigned" },
      labels: ["ready-for-agent"],
    },
    {
      id: "github-issue:112",
      title: "Execute active Unit mechanics through Battle Acts and reactions",
      lifecycle: "open",
      parentTaskId: "github-issue:48",
      prerequisiteIds: ["github-issue:110"],
      assignment: { tag: "Unassigned" },
      labels: ["ready-for-agent"],
    },
    {
      id: "github-issue:113",
      title:
        "Project Stat Block mechanics into typed creatures and available Acts",
      lifecycle: "open",
      parentTaskId: "github-issue:49",
      prerequisiteIds: ["github-issue:25"],
      assignment: { tag: "Unassigned" },
      labels: [],
    },
    {
      id: "github-issue:114",
      title: "Execute typed Stat Block attack and multi-part Act procedures",
      lifecycle: "open",
      parentTaskId: "github-issue:49",
      prerequisiteIds: ["github-issue:113"],
      assignment: { tag: "Unassigned" },
      labels: ["ready-for-agent"],
    },
    {
      id: "github-issue:115",
      title:
        "Thread authored selection and parsed mechanics through composition",
      lifecycle: "open",
      parentTaskId: "github-issue:50",
      prerequisiteIds: [
        "github-issue:114",
        "github-issue:113",
        "github-issue:112",
        "github-issue:111",
        "github-issue:110",
        "github-issue:109",
        "github-issue:47",
      ],
      assignment: { tag: "Unassigned" },
      labels: ["ready-for-agent"],
    },
    {
      id: "github-issue:116",
      title:
        "Separate durable Character Sheet facts from encounter Execution State",
      lifecycle: "open",
      parentTaskId: "github-issue:50",
      prerequisiteIds: ["github-issue:115"],
      assignment: { tag: "Unassigned" },
      labels: ["ready-for-agent"],
    },
    {
      id: "github-issue:117",
      title:
        "Bind selected Authored Mechanics Graphs from the admitted catalog",
      lifecycle: "open",
      parentTaskId: "github-issue:54",
      prerequisiteIds: ["github-issue:53", "github-issue:52"],
      assignment: { tag: "Unassigned" },
      labels: ["ready-for-agent"],
    },
    {
      id: "github-issue:118",
      title: "Discover dynamic availability from bound admitted mechanics",
      lifecycle: "open",
      parentTaskId: "github-issue:54",
      prerequisiteIds: ["github-issue:117"],
      assignment: { tag: "Unassigned" },
      labels: ["ready-for-agent"],
    },
    {
      id: "github-issue:119",
      title: "Preserve the typed Magic Missile cross-record interruption rule",
      lifecycle: "open",
      parentTaskId: "github-issue:57",
      prerequisiteIds: ["github-issue:56"],
      assignment: { tag: "Unassigned" },
      labels: ["ready-for-agent"],
    },
    {
      id: "github-issue:120",
      title:
        "Resume interrupted procedures through the shared damage lifecycle",
      lifecycle: "open",
      parentTaskId: "github-issue:57",
      prerequisiteIds: ["github-issue:107", "github-issue:56"],
      assignment: { tag: "Unassigned" },
      labels: ["ready-for-agent"],
    },
    {
      id: "github-issue:121",
      title:
        "Enter Characters and Stat Blocks into stateless Oracle Battle evaluation",
      lifecycle: "open",
      parentTaskId: "github-issue:63",
      prerequisiteIds: ["github-issue:62"],
      assignment: { tag: "Unassigned" },
      labels: ["ready-for-agent"],
    },
    {
      id: "github-issue:122",
      title:
        "Trace selected Oracle Acts through Runtime Hole continuation replay",
      lifecycle: "open",
      parentTaskId: "github-issue:63",
      prerequisiteIds: ["github-issue:121"],
      assignment: { tag: "Unassigned" },
      labels: ["ready-for-agent"],
    },
    {
      id: "github-issue:156",
      title:
        "Replace Encounter Side with rule-local Battle relationship decisions",
      lifecycle: "open",
      parentTaskId: "github-issue:92",
      prerequisiteIds: [],
      assignment: { tag: "Unassigned" },
      labels: [],
    },
    {
      id: "github-issue:157",
      title:
        "Replace authored Battle replay keys with typed execution references",
      lifecycle: "open",
      parentTaskId: "github-issue:92",
      prerequisiteIds: [],
      assignment: { tag: "Unassigned" },
      labels: [],
    },
    {
      id: "github-issue:158",
      title: "Complete exact Character Creation Oracle facts from their owner",
      lifecycle: "closed",
      parentTaskId: "github-issue:92",
      prerequisiteIds: [],
      assignment: { tag: "Unassigned" },
      labels: [],
    },
    {
      id: "github-issue:159",
      title:
        "Make fresh Character Sheet construction return exact facts and flat accumulated issues",
      lifecycle: "closed",
      parentTaskId: "github-issue:92",
      prerequisiteIds: [],
      assignment: { tag: "Unassigned" },
      labels: [],
    },
    {
      id: "github-issue:160",
      title:
        "Make Character-Sheet-to-Battle entry return origin-correct mechanical facts",
      lifecycle: "open",
      parentTaskId: "github-issue:92",
      prerequisiteIds: ["github-issue:170", "github-issue:171"],
      assignment: { tag: "Unassigned" },
      labels: ["ready-for-agent"],
    },
    {
      id: "github-issue:161",
      title:
        "Separate committed BattleSnapshot from the production continuation frontier",
      lifecycle: "open",
      parentTaskId: "github-issue:92",
      prerequisiteIds: ["github-issue:157", "github-issue:156"],
      assignment: { tag: "Unassigned" },
      labels: [],
    },
    {
      id: "github-issue:162",
      title:
        "Replace relationship partitions in Battle target and Act discovery",
      lifecycle: "closed",
      parentTaskId: "github-issue:156",
      prerequisiteIds: [],
      assignment: { tag: "Unassigned" },
      labels: ["ready-for-agent"],
    },
    {
      id: "github-issue:163",
      title:
        "Replace relationship partitions in Battle roll and trigger resolution",
      lifecycle: "closed",
      parentTaskId: "github-issue:156",
      prerequisiteIds: [],
      assignment: { tag: "Unassigned" },
      labels: [],
    },
    {
      id: "github-issue:164",
      title:
        "Replace relationship partitions in Battle effect and zero-HP lifecycles",
      lifecycle: "closed",
      parentTaskId: "github-issue:156",
      prerequisiteIds: [],
      assignment: { tag: "Unassigned" },
      labels: ["ready-for-agent"],
    },
    {
      id: "github-issue:165",
      title:
        "Give Stat Block procedures and limited-use pools typed execution references",
      lifecycle: "closed",
      parentTaskId: "github-issue:157",
      prerequisiteIds: [],
      assignment: { tag: "Unassigned" },
      labels: [],
    },
    {
      id: "github-issue:166",
      title: "Define deterministic stateless Battle continuation replay",
      lifecycle: "open",
      parentTaskId: "github-issue:161",
      prerequisiteIds: ["github-issue:170"],
      assignment: { tag: "Unassigned" },
      labels: ["ready-for-agent"],
    },
    {
      id: "github-issue:167",
      title:
        "Migrate discovered Battle Acts and replay to typed execution references",
      lifecycle: "open",
      parentTaskId: "github-issue:157",
      prerequisiteIds: ["github-issue:165"],
      assignment: { tag: "Unassigned" },
      labels: [],
    },
    {
      id: "github-issue:168",
      title:
        "Publish the exclusive Battle continuation frontier beside BattleSnapshot",
      lifecycle: "open",
      parentTaskId: "github-issue:161",
      prerequisiteIds: ["github-issue:169", "github-issue:166"],
      assignment: { tag: "Unassigned" },
      labels: ["ready-for-agent"],
    },
    {
      id: "github-issue:169",
      title: "Purify BattleSnapshot as committed mechanical state",
      lifecycle: "open",
      parentTaskId: "github-issue:161",
      prerequisiteIds: ["github-issue:170", "github-issue:171"],
      assignment: { tag: "Unassigned" },
      labels: ["ready-for-agent"],
    },
    {
      id: "github-issue:170",
      title:
        "Purge authored-name Battle replay keys and publish presentation joins",
      lifecycle: "open",
      parentTaskId: "github-issue:157",
      prerequisiteIds: [
        "github-issue:174",
        "github-issue:173",
        "github-issue:172",
      ],
      assignment: { tag: "Unassigned" },
      labels: ["ready-for-agent"],
    },
    {
      id: "github-issue:171",
      title:
        "Remove Encounter Side from Battle setup, state, and QNT vocabulary",
      lifecycle: "open",
      parentTaskId: "github-issue:156",
      prerequisiteIds: [
        "github-issue:164",
        "github-issue:163",
        "github-issue:162",
      ],
      assignment: { tag: "Unassigned" },
      labels: ["ready-for-agent"],
    },
    {
      id: "github-issue:172",
      title:
        "Migrate weapon and attack Battle subjects to execution references",
      lifecycle: "closed",
      parentTaskId: "github-issue:167",
      prerequisiteIds: ["github-issue:165"],
      assignment: { tag: "Unassigned" },
      labels: [],
    },
    {
      id: "github-issue:173",
      title:
        "Migrate spell, Unit, and feature Battle subjects to execution references",
      lifecycle: "closed",
      parentTaskId: "github-issue:167",
      prerequisiteIds: ["github-issue:165"],
      assignment: { tag: "Unassigned" },
      labels: [],
    },
    {
      id: "github-issue:174",
      title:
        "Migrate Battle threats and nested interruption transport to execution references",
      lifecycle: "closed",
      parentTaskId: "github-issue:167",
      prerequisiteIds: ["github-issue:165"],
      assignment: { tag: "Unassigned" },
      labels: [],
    },
  ],
} as const satisfies TaskDagRevision;
