-- Generated by ../generate-journal-events.mjs; do not edit.
module JournalEventsGenerated where

open import Journal

event-witnesses : List Event
event-witnesses =
  act (claimIntentRecorded a 0) ::
  act (claimReleaseIntentRecorded a 0) ::
  act (attemptPlanned a 0 0) ::
  act (workAdmitted a 0) ::
  act (suspensionRequested a 0) ::
  act (resumeRequested a 0) ::
  act (worktreeIntentRecorded a 0) ::
  act (integrationSessionOpened a 0) ::
  act (promotionIntentRecorded a 0) ::
  act (candidateConstructionNonConvergent a staleTargetHead) ::
  act (deliverySettled a) ::
  act (workflowRunBegun 0 0) ::
  act (workflowRunTerminated 0) ::
  act (capacityRevised 0) ::
  act (directionApplied 0 pause) ::
  occ (trackerFactsObserved [] [] true 0) ::
  occ (claimRecordRead a 0 0) ::
  occ (claimedTaskEligibilityObserved a 0) ::
  occ (claimedTaskIneligible a notOpen) ::
  occ (worktreeReconciliationObserved a 0 created) ::
  occ (executorReported a 0 running) ::
  occ (promotionOutcomeObserved a 0) ::
  occ (targetHeadObserved 0) ::
  []
