/** Generated by scripts/generate-formal-command-inventory.mjs from the executable Quint manifest and hosted shard families. */
export const formalCommandCount = 137
/** Character at each command position names its hosted shard. */
export const formalShardByPosition =
  "00000000000000000000000000000000000001111100000111111111111100000111111111111111111111000001111111111111111111000001111111111110000000000"
