/** Generated by scripts/generate-formal-command-inventory.mjs from the executable Quint manifest and hosted shard families. */
export const formalCommandCount = 127
/** Character at each command position names its hosted shard. */
export const formalShardByPosition =
  "0000000000000000000000000000000000000111110000011111111111110000011111111111111111111100000111111111111111111100000111111111111"
