/** Generated by scripts/generate-formal-command-inventory.mjs from the executable Quint manifest and hosted shard families. */
export const formalCommandCount = 147
/** Character at each command position names its hosted shard. */
export const formalShardByPosition =
  "000000000000000000000000000000000000011111000001111111111111000001111111111111111111110000011111111111111111110000022222222222220000000000111111111"
