-- Generated by ../generate-journal-events.mjs; do not edit.
import Journal
open Journal

def eventWitnesses : List Event := [
  .claimIntentRecorded 0 0,
  .claimReleaseIntentRecorded 0 0,
  .attemptPlanned 0 0 0,
  .workAdmitted 0 0,
  .suspensionRequested 0 0,
  .resumeRequested 0 0,
  .worktreeIntentRecorded 0 0,
  .integrationSessionOpened 0 0,
  .promotionIntentRecorded 0 0,
  .candidateConstructionNonConvergent 0 .staleTargetHead,
  .deliverySettled 0,
  .workflowRunBegun 0 0,
  .workflowRunTerminated 0,
  .capacityRevised 0,
  .directionApplied 0 .pause,
  .trackerFactsObserved [] [] true 0,
  .claimRecordRead 0 0 0,
  .claimedTaskEligibilityObserved 0 0,
  .claimedTaskIneligible 0 .notOpen,
  .worktreeReconciliationObserved 0 0 .created,
  .executorReported 0 0 .running,
  .promotionOutcomeObserved 0 0,
  .targetHeadObserved 0
]

example : eventWitnesses.length = 23 := by decide
